### ISSUE TITLE
FATAL: Chef::Exceptions::Exec: package[exim4]

### ISSUE THREAD

**Issue by stephanecollot** [rosenfeld/gitorious-cookbooks#23]
Hi

I have this error :

root@machie:~/chef-solo# chef-solo
[2012-08-06T21:01:57+02:00] INFO: **\* Chef 10.12.0 ***
[2012-08-06T21:02:00+02:00] INFO: Setting the run_list to ["recipe[vim]", "recipe[custom_environment]", "recipe[ntpdate]", "recipe[smtp]", "recipe[gitorious]"] from JSON
[2012-08-06T21:02:00+02:00] INFO: Run List is [recipe[vim], recipe[custom_environment], recipe[ntpdate], recipe[smtp], recipe[gitorious]]
[2012-08-06T21:02:00+02:00] INFO: Run List expands to [vim, custom_environment, ntpdate, smtp, gitorious]
[2012-08-06T21:02:00+02:00] INFO: Starting Chef Run for machine
[2012-08-06T21:02:00+02:00] INFO: Running start handlers
[2012-08-06T21:02:00+02:00] INFO: Start handlers complete.
[2012-08-06T21:02:00+02:00] INFO: Processing package[vim] action install (vim::default line 20)
[2012-08-06T21:02:00+02:00] INFO: Processing cookbook_file[/etc/vim/vimrc.local] action create (vim::default line 22)
[2012-08-06T21:02:00+02:00] INFO: cookbook_file[/etc/vim/vimrc.local] created file /etc/vim/vimrc.local
[2012-08-06T21:02:00+02:00] INFO: Processing ruby_block[Update editor alternatives to vim] action create (vim::default line 29)
[2012-08-06T21:02:00+02:00] INFO: ruby_block[Update editor alternatives to vim] called
[2012-08-06T21:02:00+02:00] INFO: Processing execute[update-alternatives --set editor /usr/bin/vim.basic] action run (vim::default line 28)
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in manual mode.
[2012-08-06T21:02:00+02:00] INFO: execute[update-alternatives --set editor /usr/bin/vim.basic] ran successfully
[2012-08-06T21:02:00+02:00] INFO: Processing package[bash-completion] action install (custom_environment::default line 1)
[2012-08-06T21:02:00+02:00] INFO: Processing cookbook_file[/etc/profile.d/bash-config.sh] action create (custom_environment::default line 3)
[2012-08-06T21:02:00+02:00] INFO: cookbook_file[/etc/profile.d/bash-config.sh] mode changed to 644
[2012-08-06T21:02:00+02:00] INFO: cookbook_file[/etc/profile.d/bash-config.sh] created file /etc/profile.d/bash-config.sh
[2012-08-06T21:02:00+02:00] INFO: Processing execute[ntpdate-debian] action nothing (ntpdate::default line 1)
[2012-08-06T21:02:00+02:00] INFO: Processing package[ntpdate] action install (ntpdate::default line 2)
[2012-08-06T21:02:00+02:00] INFO: Processing package[exim4] action install (smtp::default line 1)
[2012-08-06T21:02:01+02:00] ERROR: package[exim4](smtp::default line 1) has had an error
[2012-08-06T21:02:01+02:00] ERROR: package[exim4](/root/chef-solo/cookbooks/smtp/recipes/default.rb:1:in `from_file') had an error:
package[exim4](smtp::default line 1) had an error: Chef::Exceptions::Exec: apt-get -q -y install exim4=4.72-6+squeeze2 returned 100, expected 0
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/command.rb:128:in `handle_command_failures'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/command.rb:75:in`run_command'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/command.rb:143:in `run_command_with_systems_locale'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/package/apt.rb:94:in`install_package'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/package.rb:59:in `action_install'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in`send'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:49:in`run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in`each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:94:in`execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:92:in`execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:80:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:330:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:163:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:207:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application.rb:70:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/chef-solo:25
/usr/bin/chef-solo:19:in`load'
/usr/bin/chef-solo:19
[2012-08-06T21:02:01+02:00] ERROR: Running exception handlers
[2012-08-06T21:02:01+02:00] ERROR: Exception handlers complete
[2012-08-06T21:02:01+02:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2012-08-06T21:02:01+02:00] FATAL: Chef::Exceptions::Exec: package[exim4](smtp::default line 1) had an error: Chef::Exceptions::Exec: apt-get -q -y install exim4=4.72-6+squeeze2 returned 100, expected 0

Some one had quiet the same error :
https://groups.google.com/forum/#!msg/gitorious/Hr0e2teN4iE/zS-PdMmU7gIJ
I will try to disable exim later.

Thanks in advance

**Comment by rosenfeld** [comment]
If you don't want to set up exim, just get it out of the run list in line 33 here:

https://gist.github.com/847256#file_chef_gitorious_node_debian.json

But it is more likely it was a temporary problem when installed the required packages. You could try to re-run chef-solo. If it doesn't work, try to run the command yourself to see what is the error all about:

``` shell
apt-get -q -y install exim4=4.72-6+squeeze2
```

**Comment by stephanecollot** [comment]
Hi

Thank you for your prompt response.

root @ machine: ~ / chef-solo # apt-get-q-y install exim4 4.72-6 + = squeeze2
Reading package lists ...
Building dependency tree ...
Reading state information ...
Some packages could not be installed. This can mean
you have requested an impossible situation or if you use
the unstable distribution that some required packages have not yet
been created or are not out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
  exim4: Depends: exim4-base (> = 4.72) but will not install
          Depends: exim4-daemon-light but will not install or
                   exim4-daemon-heavy, but will not install or
                   exim4-daemon-custom but it is not installable
E: Broken packages

I work with a debian 6.0.5

**Comment by rosenfeld** [comment]
I've tried on 6.0.5 a few weeks ago and it worked for me. Try to `apt-get update` first before running `chef-solo` again. Most likely 4.72 is not the current version anymore. You should be able to install exim4 for this recipe to work (`apt-get install exim4`)

**Comment by stephanecollot** [comment]
I have the same error, even with "apt-get install exim4"

root@machine:~/chef-solo# apt-get update
Atteint ftp://ftp.debian.ikoula.com squeeze Release.gpg
RÃ©ception deÂ : 1 ftp://ftp.debian.ikoula.com/debian/ squeeze/contrib Translation-en
Ign ftp://ftp.debian.ikoula.com/debian/ squeeze/contrib Translation-en
RÃ©ception deÂ : 2 ftp://ftp.debian.ikoula.com/debian/ squeeze/contrib Translation-fr
Ign ftp://ftp.debian.ikoula.com/debian/ squeeze/contrib Translation-fr
RÃ©ception deÂ : 3 ftp://ftp.debian.ikoula.com/debian/ squeeze/main Translation-en
Ign ftp://ftp.debian.ikoula.com/debian/ squeeze/main Translation-en
Atteint ftp://ftp.debian.ikoula.com/debian/ squeeze/main Translation-fr
RÃ©ception deÂ : 4 ftp://ftp.debian.ikoula.com/debian/ squeeze/non-free Translation-en
Ign ftp://ftp.debian.ikoula.com/debian/ squeeze/non-free Translation-en
RÃ©ception deÂ : 5 ftp://ftp.debian.ikoula.com/debian/ squeeze/non-free Translation-fr
Ign ftp://ftp.debian.ikoula.com/debian/ squeeze/non-free Translation-fr
Atteint ftp://ftp.debian.ikoula.com squeeze Release
Atteint ftp://ftp.debian.ikoula.com squeeze/main Sources
Atteint ftp://ftp.debian.ikoula.com squeeze/contrib Sources
Atteint ftp://ftp.debian.ikoula.com squeeze/non-free Sources
Atteint ftp://ftp.debian.ikoula.com squeeze/main amd64 Packages
Atteint ftp://ftp.debian.ikoula.com squeeze/contrib amd64 Packages
Atteint ftp://ftp.debian.ikoula.com squeeze/non-free amd64 Packages
Atteint http://security.debian.org squeeze/updates Release.gpg
Ign http://security.debian.org/ squeeze/updates/main Translation-en
Ign http://security.debian.org/ squeeze/updates/main Translation-fr
Ign http://security.debian.org/ squeeze/updates/non-free Translation-en
Ign http://security.debian.org/ squeeze/updates/non-free Translation-fr
Atteint http://security.debian.org squeeze/updates Release
Atteint http://security.debian.org squeeze/updates/main Sources
Atteint http://security.debian.org squeeze/updates/non-free Sources
Atteint http://security.debian.org squeeze/updates/main amd64 Packages
Atteint http://security.debian.org squeeze/updates/non-free amd64 Packages
Reading package lists ... done

It's a virtual machine (in a french hoster) with plesk etc. I should not have good repository.

**Comment by rosenfeld** [comment]
I guess that is the problem. If you change to another official repository it might work correctly. I'm closing this issue for now as it is not related to the cookbook itself.
