### ISSUE TITLE
 Config file dir.conf not properly enabled

### ISSUE THREAD

**Issue by stephanecollot** [rosenfeld/gitorious-cookbooks#24]
Hello

I have an error

root@machine:/usr/sbin# chef-solo
[2012-08-07T02:09:55+02:00] INFO: **\* Chef 10.12.0 ***
[2012-08-07T02:09:55+02:00] INFO: Setting the run_list to ["recipe[vim]", "recipe[custom_environment]", "recipe[ntpdate]", "recipe[gitorious]"] from JSON
[2012-08-07T02:09:55+02:00] INFO: Run List is [recipe[vim], recipe[custom_environment], recipe[ntpdate], recipe[gitorious]]
[2012-08-07T02:09:55+02:00] INFO: Run List expands to [vim, custom_environment, ntpdate, gitorious]
[2012-08-07T02:09:55+02:00] INFO: Starting Chef Run for 53563hpv163139
[2012-08-07T02:09:55+02:00] INFO: Running start handlers
[2012-08-07T02:09:55+02:00] INFO: Start handlers complete.
[2012-08-07T02:09:55+02:00] INFO: Processing package[vim] action install (vim::default line 20)
[2012-08-07T02:09:55+02:00] INFO: Processing cookbook_file[/etc/vim/vimrc.local] action create (vim::default line 22)
[2012-08-07T02:09:55+02:00] INFO: Processing ruby_block[Update editor alternatives to vim] action create (vim::default line 29)
[2012-08-07T02:09:55+02:00] INFO: Processing package[bash-completion] action install (custom_environment::default line 1)
[2012-08-07T02:09:55+02:00] INFO: Processing cookbook_file[/etc/profile.d/bash-config.sh] action create (custom_environment::default line 3)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[ntpdate-debian] action nothing (ntpdate::default line 1)
[2012-08-07T02:09:55+02:00] INFO: Processing package[ntpdate] action install (ntpdate::default line 2)
[2012-08-07T02:09:55+02:00] INFO: Processing package[apache2] action install (apache2::default line 20)
[2012-08-07T02:09:55+02:00] INFO: Processing service[apache2] action enable (apache2::default line 32)
[2012-08-07T02:09:55+02:00] INFO: Processing directory[/etc/apache2/ssl] action create (apache2::default line 118)
[2012-08-07T02:09:55+02:00] INFO: Processing directory[/etc/apache2/conf.d] action create (apache2::default line 125)
[2012-08-07T02:09:55+02:00] INFO: Processing directory[/var/cache/apache2] action create (apache2::default line 132)
[2012-08-07T02:09:55+02:00] INFO: Processing template[apache2.conf] action create (apache2::default line 138)
[2012-08-07T02:09:55+02:00] INFO: Processing template[security] action create (apache2::default line 152)
[2012-08-07T02:09:55+02:00] INFO: Processing template[charset] action create (apache2::default line 162)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/ports.conf] action create (apache2::default line 172)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/sites-available/default] action create (apache2::default line 181)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/mods-available/status.conf] action create (apache2::mod_status line 21)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod status] action run (apache2::mod_status line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/mods-available/alias.conf] action create (apache2::mod_alias line 21)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod alias] action run (apache2::mod_alias line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod auth_basic] action run (apache2::mod_auth_basic line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod authn_file] action run (apache2::mod_authn_file line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod authz_default] action run (apache2::mod_authz_default line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod authz_groupfile] action run (apache2::mod_authz_groupfile line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod authz_host] action run (apache2::mod_authz_host line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod authz_user] action run (apache2::mod_authz_user line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/mods-available/autoindex.conf] action create (apache2::mod_autoindex line 21)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod autoindex] action run (apache2::mod_autoindex line 28)
[2012-08-07T02:09:55+02:00] INFO: Processing template[/etc/apache2/mods-available/dir.conf] action create (apache2::mod_dir line 21)
[2012-08-07T02:09:55+02:00] INFO: Processing execute[a2enmod dir] action run (apache2::mod_dir line 28)
[2012-08-07T02:09:56+02:00] ERROR: execute[a2enmod dir](apache2::mod_dir line 28) has had an error
[2012-08-07T02:09:56+02:00] ERROR: execute[a2enmod dir](/root/chef-solo/cookbooks/apache2/definitions/apache_module.rb:28:in `from_file') had an error:
execute[a2enmod dir](apache2::mod_dir line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/a2enmod dir ----
STDOUT:
STDERR: ERROR: Config file dir.conf not properly enabled: /etc/apache2/mods-enabled/dir.conf is a real file, not touching it
---- End output of /usr/sbin/a2enmod dir ----
Ran /usr/sbin/a2enmod dir returned 1
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:248:in `invalid!'
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:234:in`error!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/execute.rb:58:in`action_run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in`run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:49:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:80:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:330:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:163:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:207:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in`loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application.rb:70:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/chef-solo:25
/usr/bin/chef-solo:19:in `load'
/usr/bin/chef-solo:19
[2012-08-07T02:09:56+02:00] ERROR: Running exception handlers
[2012-08-07T02:09:56+02:00] ERROR: Exception handlers complete
[2012-08-07T02:09:56+02:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2012-08-07T02:09:56+02:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[a2enmod dir](apache2::mod_dir line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/a2enmod dir ----
STDOUT:
STDERR: ERROR: Config file dir.conf not properly enabled: /etc/apache2/mods-enabled/dir.conf is a real file, not touching it
---- End output of /usr/sbin/a2enmod dir ----
Ran /usr/sbin/a2enmod dir returned 1

Here are some extracts of files that are concerned
root@machine:/etc/apache2/mods-enabled# vim dir.conf
<code><pre>
IfModule mod_dir.c>
DirectoryIndex at_domains_index.html index.html index.cgi index.pl index.php index.xhtml index.htm index.shtml index.cfm
/IfModule>
</pre></code>

root@machine:/usr/sbin# vim a2enmod
  1 #!/usr/bin/perl -w
  2 #
  3 # a2enmod by Stefan Fritsch sf@debian.org
  4 # Licensed under Apache License 2.0
  5
  6 use strict;
  7 use Cwd 'realpath';
  8 use File::Spec;
  9 use File::Basename;
 10 use Getopt::Long;
 11
 12 my $quiet;
 13 my $force;
 14 Getopt::Long::Configure('bundling');
 15 GetOptions(
 16     'quiet|q' => \$quiet,
 17     'force|f' => \$force
 18 ) or exit 2;
 19
 20 my $basename = basename($0);
 21 $basename =~ /^a2(en|dis)(mod|site)((?:-.+)?)$/
 22     or die "$basename call name unknown\n";
 23 my $act        = $1;
 24 my $obj        = $2;
 25 my $dir_suffix = $3;
 26
 27 my $env_file = $ENV{APACHE_ENVVARS}
 28     || (
 29     $ENV{APACHE_CONFDIR}
 30     ? "$ENV{APACHE_CONFDIR}/envvars"
 31     : "/etc/apache2$dir_suffix/envvars"
 32     );
 33 $ENV{LANG}='C';
 34 read_env_file($env_file);
 35
 36 $act .= 'able';
 37 my ( $name, $dir, $sffx, $reload );
 38 if ( $obj eq 'mod' ) {
 39     $obj    = 'module';
 40     $dir    = 'mods';
 41     $sffx   = '.load';
 42     $reload = 'restart';

This is probably due to my preconfigured system.

bye

**Comment by rosenfeld** [comment]
Yes, your system seems to be a bit messy. For instance, in Debian usually files under /etc/apache2/mods-enabled are all symbolic links which is not the case for you.

Sorry, but I can't support every setup and I'm aiming only on latest vanilla Debian. I don't have much free time to support anything but that, sorry. I'm closing this issue because I won't be working on it. If you come with an elegant patch that will make it work with your set-up I can consider merging it.
