### ISSUE TITLE
Error with bundle install on rots

### ISSUE THREAD

**Issue by gaffo** [rosenfeld/gitorious-cookbooks#25]
```
[2012-08-10T00:45:46+00:00] INFO: script[setup ultrasphinx for Gitorious] ran successfully
[2012-08-10T00:45:46+00:00] INFO: script[setup ultrasphinx for Gitorious] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued
[2012-08-10T00:45:46+00:00] INFO: Processing template[/etc/init.d/git-ultrasphinx] action create (gitorious::default line 163)
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-ultrasphinx] mode changed to 755
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-ultrasphinx] updated content
[2012-08-10T00:45:46+00:00] INFO: Processing template[/etc/init.d/git-daemon] action create (gitorious::default line 163)
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-daemon] mode changed to 755
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-daemon] updated content
[2012-08-10T00:45:46+00:00] INFO: Processing template[/etc/init.d/git-poller] action create (gitorious::default line 163)
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-poller] mode changed to 755
[2012-08-10T00:45:46+00:00] INFO: template[/etc/init.d/git-poller] updated content
[2012-08-10T00:45:46+00:00] INFO: Processing cron[gitorious_ultrasphinx_reindexing] action create (gitorious::default line 170)
[2012-08-10T00:45:46+00:00] INFO: cron[gitorious_ultrasphinx_reindexing] added crontab entry
[2012-08-10T00:45:46+00:00] INFO: Processing service[git-ultrasphinx] action enable (gitorious::default line 175)
[2012-08-10T00:45:46+00:00] INFO: service[git-ultrasphinx] enabled
[2012-08-10T00:45:46+00:00] INFO: Processing service[git-ultrasphinx] action start (gitorious::default line 175)
[2012-08-10T00:45:48+00:00] INFO: service[git-ultrasphinx] started
[2012-08-10T00:45:48+00:00] INFO: Processing service[git-daemon] action enable (gitorious::default line 181)
[2012-08-10T00:45:48+00:00] INFO: service[git-daemon] enabled
[2012-08-10T00:45:48+00:00] INFO: Processing service[git-daemon] action start (gitorious::default line 181)
[2012-08-10T00:45:53+00:00] ERROR: service[git-daemon] (gitorious::default line 181) has had an error
[2012-08-10T00:45:53+00:00] ERROR: service[git-daemon] (/root/chef-solo/cookbooks/gitorious/recipes/default.rb:181:in `from_file') had an error:
service[git-daemon] (gitorious::default line 181) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/git-daemon start ----
STDOUT: Starting git-daemon: failure
STDERR: /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:574:in `load_spec_files': https://github.com/roman/rots.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError)
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:372:in `local_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:557:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:207:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:202:in `each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:202:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/index.rb:9:in `build'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:198:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:130:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:172:in `specs_for'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:161:in `requested_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/environment.rb:23:in `requested_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/runtime.rb:11:in `setup'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler.rb:107:in `setup'
    from /var/www/gitorious/script/../config/../config/preinitializer.rb:16
    from /var/www/gitorious/script/../config/boot.rb:28:in `load'
    from /var/www/gitorious/script/../config/boot.rb:28:in `preinitialize'
    from /var/www/gitorious/script/../config/boot.rb:10:in `boot!'
    from /var/www/gitorious/script/../config/boot.rb:123
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
    from /var/www/gitorious/script/../config/environment.rb:11
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
    from /var/www/gitorious/script/git-daemon:11
---- End output of /etc/init.d/git-daemon start ----
Ran /etc/init.d/git-daemon start returned 1
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:248:in `invalid!'
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:234:in `error!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/service/init.rb:40:in `start_service'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/service.rb:57:in `action_start'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:49:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:80:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:330:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:163:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:207:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application.rb:70:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/chef-solo:25
/usr/bin/chef-solo:19:in `load'
/usr/bin/chef-solo:19
[2012-08-10T00:45:53+00:00] ERROR: Running exception handlers
[2012-08-10T00:45:53+00:00] ERROR: Exception handlers complete
[2012-08-10T00:45:53+00:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2012-08-10T00:45:53+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[git-daemon] (gitorious::default line 181) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/git-daemon start ----
STDOUT: Starting git-daemon: failure
STDERR: /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:574:in `load_spec_files': https://github.com/roman/rots.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError)
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:372:in `local_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/source.rb:557:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:207:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:202:in `each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:202:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/index.rb:9:in `build'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:198:in `index'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:130:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:172:in `specs_for'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/definition.rb:161:in `requested_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/environment.rb:23:in `requested_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler/runtime.rb:11:in `setup'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.1.5/lib/bundler.rb:107:in `setup'
    from /var/www/gitorious/script/../config/../config/preinitializer.rb:16
    from /var/www/gitorious/script/../config/boot.rb:28:in `load'
    from /var/www/gitorious/script/../config/boot.rb:28:in `preinitialize'
    from /var/www/gitorious/script/../config/boot.rb:10:in `boot!'
    from /var/www/gitorious/script/../config/boot.rb:123
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
    from /var/www/gitorious/script/../config/environment.rb:11
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
    from /var/www/gitorious/script/git-daemon:11
---- End output of /etc/init.d/git-daemon start ----
Ran /etc/init.d/git-daemon start returned 1
```

**Comment by gaffo** [comment]
Looks like it's a test lib

**Comment by rosenfeld** [comment]
Yes, it is, I've introduced Rots in Gitorious long ago :) You could just disable it in your Gemfile and try again, but I have no idea why sometimes people have ROTS-related trouble running "bundle"...

What does it happen if you try to run "bundle" manually?

**Comment by gaffo** [comment]
It seems to install fine when I just bundle install it but not if I do the recipe. It seems the recipe pulls over the top of the file every time so I'll have to disable that and try it out. This is on Ubuntu 12.04 image on EC2

**Comment by gaffo** [comment]
So just did an install on a fresh ec2 box and same issue. However, I then went in as the git user to the /var/www/gitorious and did a 

```
bundle install --without test
```

And then went back to root and did another chef-solo and everything seemed to go through correctly.

**Comment by rosenfeld** [comment]
I just ask the recipe to run bundler:

https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L90

I have no idea on how to properly handle any possible failures caused by network issues or alikes. Actually I'm thinking about removing the "--without test" as it isn't much helpful as Bundler still needs to resolve the tests dependencies too...

This problem doesn't happen always. For some reason when the Gemfile includes some gem pointing to a GitHub location it is more likely to cause issues like this... :(

We don't use a gem from RubyGems because rots wasn't released to RubyGems.org. I've just asked them to do that:

https://github.com/roman/rots/issues/4

Hopefully this could improve the situation of installing Gitorious and avoid issues like this...
