### ISSUE TITLE
Recipe Compile Error

### ISSUE THREAD

**Issue by linse** [rosenfeld/gitorious-cookbooks#29]
Hi, unfortunately I get an error when I run chef-solo with your recipe on my Debian squeeze:

``` bash
linse /root/chef-solo/cookbooks $ sudo chef-solo 
Starting Chef Client, version 11.6.0
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /root/chef-solo/cookbooks/gitorious/recipes/default.rb
================================================================================


NoMethodError
-------------
undefined method `[]' for nil:NilClass


Cookbook Trace:
---------------
  /root/chef-solo/cookbooks/apache2/recipes/default.rb:118:in `from_file'
  /root/chef-solo/cookbooks/passenger_apache2/recipes/default.rb:25:in `from_file'
  /root/chef-solo/cookbooks/passenger_apache2/recipes/mod_rails.rb:25:in `from_file'
  /root/chef-solo/cookbooks/gitorious/recipes/default.rb:1:in `from_file'


Relevant File Content:
----------------------
/root/chef-solo/cookbooks/apache2/recipes/default.rb:

111:    # welcome page moved to the default-site.rb temlate
112:    file "#{node[:apache][:dir]}/conf.d/welcome.conf" do
113:      action :delete
114:      backup false
115:    end
116:  end
117:  
118>> directory "#{node[:apache][:dir]}/ssl" do
119:    action :create
120:    mode 0755
121:    owner "root"
122:    group "root"
123:  end
124:  
125:  directory "#{node[:apache][:dir]}/conf.d" do
126:    action :create
127:    mode 0755



[2013-09-12T13:43:01-05:00] ERROR: Running exception handlers
[2013-09-12T13:43:01-05:00] ERROR: Exception handlers complete
[2013-09-12T13:43:01-05:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2013-09-12T13:43:01-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by rosenfeld** [comment]
Yes, I'm aware this recipe is broken in newer Chef versions but since there's a long while I'm not using Gitorious I couldn't set up some time to fix it. If I did, I'd probably change a few things, like using nginx instead of passenger and PostgreSQL instead of MySQL... I'd glad merge any pull requests to fix the recipes.
