### ISSUE TITLE
error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by iversant** [rosenfeld/gitorious-cookbooks#7]
[Wed, 27 Jul 2011 21:17:55 -0700] ERROR: git[/var/www/gitorious](gitorious::default line 58) has had an error
[Wed, 27 Jul 2011 21:17:55 -0700] ERROR: Running exception handlers
[Wed, 27 Jul 2011 21:17:55 -0700] ERROR: Exception handlers complete
[Wed, 27 Jul 2011 21:17:55 -0700] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[Wed, 27 Jul 2011 21:17:55 -0700] FATAL: Chef::Exceptions::ShellCommandFailed: git[/var/www/gitorious](gitorious::default line 58) had an error: Expected process to exit 0, but it exited with 255
---- Begin output of git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca ----
STDOUT:
STDERR: error: cannot open .git/FETCH_HEAD: Permission denied
---- End output of git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca ----
Ran git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca returned 255
### 

 less chef-stacktrace.out
Generated at Wed Jul 27 21:32:21 -0700 2011
Chef::Exceptions::ShellCommandFailed: git[/var/www/gitorious](gitorious::default line 58) had an error: Expected process to exit 0, but it exited with 255
---- Begin output of git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca ----
STDOUT:
STDERR: error: cannot open .git/FETCH_HEAD: Permission denied
---- End output of git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca ----
Ran git fetch origin && git fetch origin --tags && git reset --hard 143643b091e6ac7ce6d6ed811467f4bbb65126ca returned 255
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/shell_out.rb:207:in `invalid!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/shell_out.rb:193:in`error!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/git.rb:135:in`fetch_updates'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/git.rb:64:in `action_sync'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource.rb:417:in`send'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource.rb:417:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/runner.rb:45:in`run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/runner.rb:78:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/runner.rb:78:in`each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/runner.rb:78:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection.rb:94:in`execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/resource_collection.rb:92:in`execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/runner.rb:76:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/client.rb:312:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/client.rb:160:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/application/solo.rb:192:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/application/solo.rb:183:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/application/solo.rb:183:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/application.rb:66:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/chef-solo:25
/usr/bin/chef-solo:19:in`load'
/usr/bin/chef-solo:19

**Comment by rosenfeld** [comment]
Strange issue, since the git cloning code is written by Chef itself... Try to "rm -rf /var/www/gitorious" and let Chef try cloning it again...
